version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Logging in to Docker Hub (if needed)..."
      # We will add Security Scans here later!
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t devsecops-app .
  post_build:
    commands:
      - echo "Build completed successfully!"